In [60]:
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# import 
# Correct Yahoo ticker for NIFTY 50

ticker = '^NSEI'

# Download daily NIFTY data from 2018 to 2024
data = yf.download(ticker, start="2015-01-01", end="2025-01-01", interval='1d')

data

/var/folders/_8/mpd74nc13t18t772krwjb9500000gn/T/ipykernel_7899/1323210307.py:11: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker, start="2015-01-01", end="2025-01-01", interval='1d')
[*********************100%***********************]  1 of 1 completed

Price              Close          High           Low          Open  Volume
Ticker             ^NSEI         ^NSEI         ^NSEI         ^NSEI   ^NSEI
Date
2015-01-02   8395.450195   8410.599609   8288.700195   8288.700195  101900
2015-01-05   8378.400391   8445.599609   8363.900391   8407.950195  118200
2015-01-06   8127.350098   8327.849609   8111.350098   8325.299805  172800
2015-01-07   8102.100098   8151.200195   8065.450195   8118.649902  164100
2015-01-08   8234.599609   8243.500000   8167.299805   8191.399902  143800
...                  ...           ...           ...           ...     ...
2024-12-24  23727.650391  23867.650391  23685.150391  23769.099609  177700
2024-12-26  23750.199219  23854.500000  23653.599609  23775.800781  177700
2024-12-27  23813.400391  23938.849609  23800.599609  23801.400391  176800
2024-12-30  23644.900391  23915.349609  23599.300781  23796.900391  364900
2024-12-31  23644.800781  23689.849609  23460.449219  23560.599609  193600

[2459 rows x 5 columns]

In [61]:
data.index

DatetimeIndex(['2015-01-02', '2015-01-05', '2015-01-06', '2015-01-07',
               '2015-01-08', '2015-01-09', '2015-01-12', '2015-01-13',
               '2015-01-14', '2015-01-15',
               ...
               '2024-12-17', '2024-12-18', '2024-12-19', '2024-12-20',
               '2024-12-23', '2024-12-24', '2024-12-26', '2024-12-27',
               '2024-12-30', '2024-12-31'],
              dtype='datetime64[ns]', name='Date', length=2459, freq=None)

In [62]:
data.columns = data.columns.droplevel(1)

In [63]:
data

Price              Close          High           Low          Open  Volume
Date
2015-01-02   8395.450195   8410.599609   8288.700195   8288.700195  101900
2015-01-05   8378.400391   8445.599609   8363.900391   8407.950195  118200
2015-01-06   8127.350098   8327.849609   8111.350098   8325.299805  172800
2015-01-07   8102.100098   8151.200195   8065.450195   8118.649902  164100
2015-01-08   8234.599609   8243.500000   8167.299805   8191.399902  143800
...                  ...           ...           ...           ...     ...
2024-12-24  23727.650391  23867.650391  23685.150391  23769.099609  177700
2024-12-26  23750.199219  23854.500000  23653.599609  23775.800781  177700
2024-12-27  23813.400391  23938.849609  23800.599609  23801.400391  176800
2024-12-30  23644.900391  23915.349609  23599.300781  23796.900391  364900
2024-12-31  23644.800781  23689.849609  23460.449219  23560.599609  193600

[2459 rows x 5 columns]

In [64]:
# Save to CSV
data.to_csv('nifty_data.csv')

print("Data downloaded and saved as nifty.csv")
print(data.head())

Data downloaded and saved as nifty.csv
Price             Close         High          Low         Open  Volume
Date
2015-01-02  8395.450195  8410.599609  8288.700195  8288.700195  101900
2015-01-05  8378.400391  8445.599609  8363.900391  8407.950195  118200
2015-01-06  8127.350098  8327.849609  8111.350098  8325.299805  172800
2015-01-07  8102.100098  8151.200195  8065.450195  8118.649902  164100
2015-01-08  8234.599609  8243.500000  8167.299805  8191.399902  143800

In [65]:
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# import 
# Correct Yahoo ticker for NIFTY 50
import pandas as pd

# Go one folder up, then into stock_data folder
df = pd.read_csv('../stock_data/ind_nifty50list.csv', index_col=0, parse_dates=True)
symbol=df['Symbol']
symbol.tolist()
for i in symbol:
    ticker = i+'.NS'
    # Download daily NIFTY data from 2018 to 2024
    data = yf.download(ticker, start="2020-09-01", end="2025-09-01", interval='1d')
    data.columns = data.columns.droplevel(1)
    # Save to CSV
    filename=i+'.csv'
    data.to_csv('../stock_data/'+filename)
    print(f"Data for {i} downloaded and saved as {filename}")
    print(data.head(1))

FileNotFoundError: [Errno 2] No such file or directory: '../stock_data/ind_nifty50list.csv'